// Based of the default CodeMirror stylesheet
module.exports = {
    // SourceCode:      {color: '000000', background: 'FFFFFF'},
    tokens: [
      {name: 'CodeNormal',      color: '000000'},
      {name: 'CodeAtom',        color: '221199'},
      {name: 'CodeAttribute',   color: '0000CC'},
      {name: 'CodeBracket',     color: '999977'},
      {name: 'CodeBuiltin',     color: '3300AA'},
      {name: 'CodeComment',     color: 'AA5500'},
      {name: 'CodeDef',         color: '0000FF'},
      {name: 'CodeEm',          color: '000000', italic: true},
      {name: 'CodeError',       color: 'FF0000'},
      {name: 'CodeHeader',      color: '0000FF', bold: true},
      {name: 'CodeHr',          color: '999999'},
      {name: 'CodeInvalidchar', color: 'FF0000'},
      {name: 'CodeKeyword',     color: '770088'},
      {name: 'CodeLink',        color: '0000CC', underline: true},
      {name: 'CodeMeta',        color: '555555'},
      {name: 'CodeNegative',    color: 'DD4444'},
      {name: 'CodeNumber',      color: '116644'},
      {name: 'CodeOperator',    color: '000000'},
      {name: 'CodePositive',    color: '229922'},
      {name: 'CodeProperty',    color: '000000'},
      {name: 'CodePunctuation', color: '000000'},
      {name: 'CodeQualifier',   color: '555555'},
      {name: 'CodeQuote',       color: '009900'},
      {name: 'CodeString',      color: 'AA1111'},
      {name: 'CodeStringB',     color: 'FF5500'},
      {name: 'CodeStrong',      color: '000000', bold: true},
      {name: 'CodeTag',         color: '117700'},
      {name: 'CodeVariable',    color: '000000'},
      {name: 'CodeVariableB',   color: '0055AA'},
      {name: 'CodeVariableC',   color: '008855'},
    ],
};
